=head1 NAME

nbdkit-zero-plugin - nbdkit zero length plugin

=head1 SYNOPSIS

 nbdkit zero

=head1 DESCRIPTION

C<nbdkit-zero-plugin> is a zero length plugin for L<nbdkit(1)>.  It
presents a virtual device of length zero bytes.

This plugin is mainly good for testing corner cases in nbdkit, the NBD
protocol and NBD clients.

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-plugin(3)>,
L<nbdkit-null-plugin(1)>,
L<nbdkit-pattern-plugin(1)>,
L<nbdkit-random-plugin(1)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2018 Red Hat Inc.
