=head1 NAME

nbdkit-delay-filter - nbdkit delay filter

=head1 SYNOPSIS

 nbdkit --filter=delay plugin rdelay=SECS wdelay=SECS [plugin-args...]

 nbdkit --filter=delay plugin rdelay=NNms wdelay=NNms [plugin-args...]

=head1 DESCRIPTION

C<nbdkit-delay-filter> is a filter that delays read and write requests
by some seconds or milliseconds.  This is used to simulate a slow or
remote server, or to test certain kinds of race conditions in Linux.

=head1 EXAMPLE

 nbdkit --filter=delay file file=disk.img rdelay=100ms wdelay=100ms

=head1 PARAMETERS

=over 4

=item B<rdelay=>SECS

=item B<rdelay=>NNB<ms>

The optional read delay in seconds or milliseconds.

=item B<wdelay=>SECS

=item B<wdelay=>NNB<ms>

The optional write delay in seconds or milliseconds.

=back

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-filter(3)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2018 Red Hat Inc.
