=head1 NAME

nbdkit-file-plugin - nbdkit file plugin

=head1 SYNOPSIS

 nbdkit file file=FILENAME

=head1 DESCRIPTION

C<nbdkit-file-plugin> is a file serving plugin for L<nbdkit(1)>.

It serves the named C<FILENAME> over NBD.

To concatenate multiple files, use L<nbdkit-split-plugin(1)>.

=head1 PARAMETERS

=over 4

=item B<file=>FILENAME

Serve the file named C<FILENAME>.  A device path can also be
used here.

This parameter is required.

=item B<rdelay>

=item B<wdelay>

These plugin parameters have been moved to the
L<nbdkit-delay-filter(1)> filter.  Modify the command line to add
I<--filter=delay> in order to use these parameters.

=back

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-plugin(3)>,
L<nbdkit-split-plugin(1)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2013 Red Hat Inc.
