=head1 NAME

nbdkit-cache-filter - nbdkit caching filter

=head1 SYNOPSIS

 nbdkit --filter=cache plugin [cache=writeback|writethrough|unsafe]
                              [plugin-args...]

=head1 DESCRIPTION

C<nbdkit-cache-filter> is a filter that adds caching on top of a
plugin.  This is useful if a plugin is slow or expensive to use,
because nbdkit will try to minimize requests to the plugin by caching
previous requests.

Note that many NBD I<clients> are able to do caching, and because the
caching happens on the client side it will usually be more effective
than caching inside the server.  This filter can be used if the client
does not have effective caching, or (with C<cache=unsafe>) to defeat
flush requests from the client (which is unsafe and can cause data
loss, as the name suggests).

=head1 PARAMETERS

=over 4

=item B<cache=writeback>

Store writes in the cache.  They are not written to the plugin unless
an explicit flush is done by the client.

This is the default caching mode, and is safe if your client issues
flush requests correctly (which is true for modern Linux and other
well-written NBD clients).

=item B<cache=writethrough>

Always force writes through to the plugin.

This makes the cache less effective, but is necessary if your client
does not issue correct flush requests.

=item B<cache=unsafe>

Ignore flush requests.  Never write to the plugin unless the cache
grows too large.

This is dangerous and can cause data loss, but this may be acceptable
if you only use it for testing or with data that you don't care about
or can cheaply reconstruct.

=back

=head1 ENVIRONMENT VARIABLES

=over 4

=item C<TMPDIR>

The cache is stored in a temporary file located in C</var/tmp> by
default.  You can override this location by setting the C<TMPDIR>
environment variable before starting nbdkit.

=back

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-file-plugin(1)>,
L<nbdkit-filter(3)>,
L<qemu-img(1)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2018 Red Hat Inc.
