=head1 NAME

nbdkit-memory-plugin - nbdkit virtual memory plugin

=head1 SYNOPSIS

 nbdkit memory size=SIZE

=head1 DESCRIPTION

C<nbdkit-memory-plugin> is a plugin for L<nbdkit(1)> which stores a
single disk image in virtual memory, and discards it when nbdkit
exits.

All nbdkit clients will see the same disk content, initially all
zeroes.

The disk image is stored in memory so it cannot be larger than
physical RAM plus swap, less whatever is being used by the rest of the
system.  Very large disk image sizes will usually not work with this
plugin (use L<nbdkit-file-plugin(1)> backed by a temporary file for
that).

This can be used for testing where you don't care about the final
content of the disk image.

=head1 PARAMETERS

=over 4

=item B<size=>SIZE

Specify the virtual size of the disk image.

This parameter is required.

=back

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-plugin(3)>,
L<nbdkit-data-plugin(1)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2017 Red Hat Inc.
