=head1 NAME

nbdkit-nofilter-filter - nbdkit passthrough filter

=head1 SYNOPSIS

 nbdkit --filter=nofilter plugin [plugin-args...]

=head1 DESCRIPTION

C<nbdkit-nofilter-filter> passes through requests unchanged.
It is mostly used for testing nbdkit.

=head1 FILES

=over 4

=item F<$filterdir/nbdkit-nofilter-filter.so>

The filter.

Use C<nbdkit --dump-config> to find the location of C<$filterdir>.

=back

=head1 VERSION

C<nbdkit-nofilter-filter> first appeared in nbdkit 1.18.

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-filter(3)>.

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
