=head1 NAME

nbdkit-example2-plugin - An example nbdkit plugin

=head1 SYNOPSIS

 nbdkit example2 file=FILENAME

=head1 DESCRIPTION

C<nbdkit-example2-plugin> is an example L<nbdkit(1)> plugin.

It serves the named C<FILENAME> over NBD, readonly.

Mainly this is useful for testing nbdkit and as an example for writing
nbdkit plugins (L<nbdkit-plugin(3)>).

=head1 SEE ALSO

L<example2.c> in the nbdkit source tree,
L<nbdkit(1)>,
L<nbdkit-plugin(3)>

=head1 AUTHORS

Richard W.M. Jones

=head1 COPYRIGHT

Copyright (C) 2013 Red Hat Inc.
