=head1 NAME

nbdkit-stats-filter - display statistics about operations

=head1 SYNOPSIS

 nbdkit --filter=stats PLUGIN statsfile=FILE
                       [statsappend=true] [statsthreshold=PERCENTILE]

=head1 DESCRIPTION

C<nbdkit-stats-filter> is a filter that displays statistics about NBD
operations, such as the number of bytes read and written.  Statistics
are written to a file once when nbdkit exits.

=head1 EXAMPLE OUTPUT

 # nbdkit --filter=exitfirst --filter=stats memory 25G statsfile=example.txt
 # nbd-client localhost /dev/nbd1 && mkfs.ext4 /dev/nbd1 &&
   nbd-client -d /dev/nbd1
 [....]
 # cat example.txt
 total: 1207 ops, 24.756059 s, 25.13 GiB, 1.02 GiB/s
 read: 101 ops, 0.000322 s, 1.64 MiB, 4.99 GiB/s op, 68.02 KiB/s total
 write: 1088 ops, 0.067040 s, 132.38 MiB, 1.93 GiB/s op, 5.35 MiB/s total
 trim: 14 ops, 0.002605 s, 25.00 GiB, 9596.93 GiB/s op, 1.01 GiB/s total
 flush: 4 ops, 0.000001 s, 0 bytes, 0 bytes/s op, 0 bytes/s total
 
 READ Request sizes:
     blocksize     request count
          4096                93 (68.38%)
         61440                 5 (3.68%)
         24576                 5 (3.68%)
          8192                 5 (3.68%)
         16384                 5 (3.68%)
        126976                 3 (2.21%)
        258048                 3 (2.21%)
         57344                 2 (1.47%)
        262144                 2 (1.47%)
         20480                 2 (1.47%)
         86016                 2 (1.47%)
         40960                 2 (1.47%)
      (others)                 7 (5.15%)
 
 WRITE Request sizes:
     blocksize     request count
        524288               264 (89.19%)
          4096                18 (6.08%)
      (others)                14 (4.73%)
 
 TRIM Request sizes:
     blocksize     request count
    2147483648                12 (85.71%)
    1056964608                 1 (7.14%)
      (others)                 1 (7.14%)
 
 ZERO Request sizes:
     blocksize     request count

=head1 PARAMETERS

=over 4

=item B<statsfile=>FILE

The file where we write the stats.

This parameter is required.

=item B<statsappend=true>

If set then we append to the file instead of replacing it.

=item B<statsthreshold=>PERCENTILE

Percentile of requests for which block size histogram should be printed.
Set to zero to disable collection of block size statistics. Set to 100
to get a list of every block size encountered. Default: 95.

=back

=head1 FILES

=over 4

=item F<$filterdir/nbdkit-stats-filter.so>

The filter.

Use C<nbdkit --dump-config> to find the location of C<$filterdir>.

=back

=head1 VERSION

C<nbdkit-stats-filter> first appeared in nbdkit 1.14.

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-filter(3)>,
L<nbdkit-log-filter(1)>.

=head1 AUTHORS

Richard W.M. Jones

Nikolaus Rath

=head1 COPYRIGHT

Copyright (C) 2019-2022 Red Hat Inc.
