=head1 NAME

nbdkit-log-filter - nbdkit log filter

=head1 SYNOPSIS

 nbdkit --filter=log plugin logfile=FILE [logappend=BOOL] [plugin-args...]

=head1 DESCRIPTION

C<nbdkit-log-filter> is a filter that logs all transactions to a file.
When used as the first filter, it can show the original client
requests.  As a later filter, it can show how earlier filters have
modified the original request.  The format of the log file is
described in L</LOG FILE FORMAT> below.

An alternative to this filter is simply to run nbdkit with the I<-f>
and I<-v> flags which enable verbose debugging to stderr.  This logs
many aspects of nbdkit operation, but requires running nbdkit in the
foreground.  The log filter uses a more parsimonious and more easily
parsable format and works when nbdkit runs in the background.

=head1 PARAMETERS

=over 4

=item B<logfile=>FILE

The file where the log is written.  This parameter is required.

=item B<logappend=true>

=item B<logappend=false>

(nbdkit E<ge> 1.8)

When set to C<false> (the default), if the file already exists it will
be truncated.  When set to C<true>, the filter appends to the existing
file.

=back

=head1 EXAMPLES

Serve the file F<disk.img>, and log each client transaction in the
file F<disk.log>:

 nbdkit --filter=log file disk.img logfile=disk.log

Repeat the task, but with the cow (copy-on-write) filter to perform
local caching of data served from the original plugin:

 nbdkit --filter=cow --filter=log file disk.img logfile=disk.log2

After running a client that performs the same operations under each of
the two servers, you can compare F<disk.log> and F<disk.log2> to see
the impact of the caching.

=head1 LOG FILE FORMAT

An example logging session of a client that requests an export list
before performing a single successful read is:

 2020-08-06 02:07:23.080415 ListExports id=1 readonly=0 tls=0 ...
 2020-08-06 02:07:23.080502 ...ListExports id=1 exports=[""] return=0
 2020-08-06 02:07:23.080712 connection=1 Connect export='' tls=0 size=0x400 write=1 flush=1 rotational=0 trim=1 zero=2 fua=2 extents=1 cache=2 fast_zero=1
 2020-08-06 02:07:23.080907 connection=1 Read id=1 offset=0x0 count=0x200 ...
 2020-08-06 02:07:23.080927 connection=1 ...Read id=1 return=0 (Success)
 2020-08-06 02:07:23.081255 connection=1 Disconnect transactions=1

All lines start with a timestamp in C<YYYY-MM-DD HH:MM:ZZ.MS> format.

For connected calls, C<connection=N> is present to distinguish
between clients.

The action follows.  Currently the following actions are logged:
ListExports, Ready, Fork, Preconnect, Connect, Read, Write, Zero,
Trim, Extents, Cache, Flush and Disconnect.

Some actions are logged across two lines showing the call and return
value.  Because nbdkit handles requests in parallel different requests
may be intermingled.  Use the C<id=N> field for correlation, it is
unique per connection.

=head1 FILES

=over 4

=item C<logfile=FILE> parameter

This filter writes to the file specified by the C<logfile=FILE>
parameter.

=item F<$filterdir/nbdkit-log-filter.so>

The filter.

Use C<nbdkit --dump-config> to find the location of C<$filterdir>.

=back

=head1 VERSION

C<nbdkit-log-filter> first appeared in nbdkit 1.4.

=head1 SEE ALSO

L<nbdkit(1)>,
L<nbdkit-file-plugin(1)>,
L<nbdkit-cow-filter(1)>,
L<nbdkit-filter(3)>,
L<nbdkit-stats-filter(1)>.

=head1 AUTHORS

Eric Blake

=head1 COPYRIGHT

Copyright (C) 2018 Red Hat Inc.
